name: Terraform Plan

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.SA_EMAIL }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init Infrastructure
        working-directory: terraform/infrastructure
        run: terraform init

      - name: Terraform Plan Infrastructure
        working-directory: terraform/infrastructure
        run: terraform plan -var="project_id=${{ vars.TF_VAR_PROJECT_ID }}"

      - name: Terraform Init App
        working-directory: terraform/app
        run: terraform init

      - name: Terraform Plan App
        working-directory: terraform/app
        run: terraform plan -var="project_id=${{ vars.TF_VAR_PROJECT_ID }}" -var="container_image=us-docker.pkg.dev/cloudrun/container/hello"
